export enum ControlType {
    //<<controltype=field sub types>>
    textBox = 'textBox',
    textArea = 'textArea',
    checkbox = 'checkbox',
    checkboxGroup = 'checkboxGroup',
    datePicker = 'datePicker',
    kzDatePicker = 'kzDatePicker',
    kzTimePicker = 'kzTimePicker',
    kzLocationPicker = 'kzLocationPicker',
    radioGroup = 'radioGroup',
    tagGroup = 'tagGroup',
    select = 'select',
    compoundSelect = 'compoundSelect',
    tagSelect = 'tagSelect',
    tags = 'tags',
    checklistSelect = 'checklistSelect',
    slider = 'slider',
    switch = 'switch',
    rating = 'rating',
    counter = 'counter',
    timepicker = 'timepicker',
    fileUpload = 'fileUpload',
    imageFileUpload = 'imageFileUpload',
    videoFileUpload = 'videoFileUpload',
    mediaFileUpload = 'mediaFileUpload',
    input = 'input',
    colorPicker = 'colorPicker',
    kzColorSelect = 'kzColorSelect',
    kzInternationalPhoneNumberSelect = 'kzInternationalPhoneNumberSelect'
  }
  